config/routes.rb
Rails.application.routes.draw do
  root(to: 'articles#index')

  resources :articles do
    resources :comments
  end

  get 'users/signup', to: 'users#new'
  resources :users, except: :new

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  MINIMUM_TITLE_LENGTH = 5

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: { minimum: MINIMUM_TITLE_LENGTH }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  MAXIMUM_NAME_LENGTH = 255
  MAXIMUM_EMAIL_LENGTH = 50
  MINIMUM_PASSWORD_LENGTH = 6

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  before_save :email_to_downcase

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_secure_password
  validates :name, presence: true, length: { maximum: MAXIMUM_NAME_LENGTH }
  validates :email, presence: true, length: { maximum: MAXIMUM_EMAIL_LENGTH },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :password, presence: true, length: { minimum: MINIMUM_PASSWORD_LENGTH }

  private

  def email_to_downcase
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.order(created_id: :desc)
    # @comment = Comment.new

  end

  def new
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      redirect_to @article # redirect_to "/articles/#{article.id}"
    else
      render :new
    end
  end

  def edit
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    @article = Article.find(params[:id])
    session_notice(:danger, 'Wrong user!') unless equal_with_current_user?(@article.user)
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    # session_notice(:danger, 'You must be logged in!') unless logged_in?
    article = Article.find(params[:id])
    # session_notice(:danger, 'Wrong user!') unless equal_with_current_user?(article.user)

    article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    session_notice(:danger, 'You must be logged in!', login_path) unless logged_in?

    @article = Article.find(params['article_id'])
    @comment = @article.comments.build
  end

  def create
    @article = Article.find(params['article_id'])
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @article
    else
      render :new
    end

  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy

    redirect_to comment.article
  end

  def edit
    session_notice(:danger, 'You must be logged in!', login_path) unless logged_in?


    @comment = Comment.find(params[:id])
    session_notice(:danger, 'Wrong user!') unless equal_with_current_user?(@comment.user)
    # @article = Article.find(params[:article_id])
    @article = @comment.article
  end

  def update
    @comment = Comment.find(params['id'])
    # @article = Article.find(params['article_id'])

    if @comment.update(comment_params)
      redirect_to @comment.article
    else
      render :new
    end

  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session_notice(:warning, 'Already logged in!') if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email])

    if user&.authenticate(params[:session][:password])
      log_in(user)
      flash[:success] = "Welcome #{user.name} !"
      redirect_to user
    else
      flash.now[:danger] = 'invalid email and password'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    session_notice(:warning, 'Already logged in!') if logged_in?

    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def articles
    current_user.articles
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def session_notice(type, message, path = root_path)
    flash[type.to_sym] = message
    redirect_to path
  end

  def equal_with_current_user?(other_user)
    current_user == other_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="column is-6 is-offset-3">

  <div class="card">
  <% unless local_assigns[:show] %>
    <header class="card-header">
      <p class="card-header-title"><%= article.title %></p>
      <p class="card-header-title has-text-weight-light">Comments (<%= article.comments.count %>)</p>
    </header>
  <% end %>
  <% if local_assigns[:show]%>
    <div class="card-content">
      <div class="content">
        <%= article.body %>
      </div>
    </div>
    <% else %>
    <div class="card-content">
      <div class="content">
        <%= article.body.truncate(70) %>
      </div>
    </div>
    <% end %>
    <footer class="card-footer">
    <% if local_assigns[:show] %>
        <% if logged_in? %>
          <%= link_to "New comment", new_article_comment_path(article), class: "card-footer-item" %>
        <% end %>
        <%= link_to "Back", root_path, class: "card-footer-item"  %>
      <% else %>
      <%= link_to "Show", article_path(article), class: "card-footer-item"  %>
    <% end%>
    <% if logged_in? && equal_with_current_user?(article.user)%>
      <%= link_to "Edit", edit_article_path(article), class: "card-footer-item" %>
      <%= link_to 'Delete',  article_path(article),
      method: :delete,
      data: { confirm: 'Are you sure?' },
      class: "card-footer-item" %>
    <% end %>
    </footer>
  </div>
</div>

app/views/articles/_form.html.erb
<%
if article.persisted?
  cancel_path = article_path(article)
else
  cancel_path = root_path
end
%>

<div class="container">
  <div class="columns is-multiline">
   <% if article.errors.any? %>
    <div class="column is-6 is-offset-3">
      <article class="message is-danger">
        <div class="message-body">
          <p>
            <%= pluralize(article.errors.count, 'error') %> prohibited this Article from being saved:
          </p><br>
            <% article.errors.full_messages.each do |elem|%>
            <li><%= elem %></li>
          <% end %>
        </div>
      </article>
    </div>
    <% end %>
    <div class="column is-6 is-offset-3">
      <div class="content">
        <h1><%= heading %></h1>
      </div>
    </div>

    <div class="column is-6 is-offset-3">
      <%= form_with model: article, local: true do |form| %>
        <div class="field">
          <%= form.label :title, class: "label"  %>
          <div class="control">
            <%= form.text_field :title, class: "input", placeholder: "Title here"  %>
          </div>
        </div>

        <div class="field">
          <%= form.label :body, class: "label" %>
          <div class="control">
             <%= form.text_area :body, class: "textarea", placeholder: "Message here"  %>
          </div>
        </div>

        <div class="field is-grouped">
          <div class="control">
            <%= form.submit submit, class: "button is-link"  %>
          </div>
          <div class="control">
            <%= link_to 'Cancel', cancel_path, class: "button is-link is-light" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<%= render 'form',
article: @article,
submit: 'Update article',
heading: 'Edit article' %>




<%# So HTML sintaksa
<%# <form action="/articles" method="post">
  <p>
  <label for="title">Title:</label><br>
  <input type="text" id="title" name="title">
  </p>

  <p>
  <label for="body">Body:</label><br>
  <textarea id="body" name="body"></textarea>
  </p>

  <p>
  <input type="submit" value="Save article">

</form> %>

app/views/articles/index.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content">
        <h1>Articles</h1>
      </div>
    </div>

      <%= render @articles %>
  </div>
</div>

app/views/articles/new.html.erb
<%= render 'form',
article: @article,
heading: 'New article',
submit: 'Save article' %>

<%# So HTML sintaksa
<%# <form action="/articles" method="post">
  <p>
  <label for="title">Title:</label><br>
  <input type="text" id="title" name="title">
  </p>

  <p>
  <label for="body">Body:</label><br>
  <textarea id="body" name="body"></textarea>
  </p>

  <p>
  <input type="submit" value="Save article">

</form> %>

app/views/articles/show.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1><%= @article.title %></h1>
      </div>
    </div>

    <%= render @article, show: true %>
    <%= render @comments %>
    <%# <%= render 'comments/form', article: @article, comment: @comment %>


  </div>
</div>

app/views/comments/_comment.html.erb
<div class="column is-6 is-offset-3">

  <div class="media-content comment">

    <div class="content">
      <p>
        <strong><%= comment.user.name %></strong> <small><%= time_ago_in_words(comment.created_at) %></small>
        <br>
        <%= comment.body %>
      </p>
    </div>
    <nav class="level is-mobile">

      <div class="level-left">
        <% if logged_in? && equal_with_current_user?(comment.user) %>
          <%= link_to edit_article_comment_path(@article, comment), class: "level-item" do %>
          <span class="icon is-small"><i class="far fa-edit"></i></span>
          <% end %>

          <%= link_to article_comment_path(@article, comment), method: :delete, class: "level item", data: { confirm: "Are you sure you want to delete this comment?" } do %>
            <span class="icon is-small"><i class="far fa-trash-alt"></i></span>
          <% end %>
        <% end %>
      </div>
    </nav>
  </div>

</div>

app/views/comments/_form.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content">
        <h1><%= article.title %><%= heading %></h1>
      </div>
    </div>

    <% if comment.errors.any? %>
      <div class="column is-6 is-offset-3">
        <article class="message is-danger">
          <div class="message-body">
            <p>
              <%= pluralize(comment.errors.count, 'error') %> prohibited this comment from being saved:
            </p><br>
              <% comment.errors.full_messages.each do |message|%>
              <li><%= message %></li>
            <% end %>
          </div>
        </article>
      </div>
    <% end %>

    <div class="column is-6 is-offset-3">
      <article class="media">
          <div class="media-content">
            <%= form_with model: [article,comment], local: true do |form| %>
             
                <div class="field">
                  <%= form.label :body, class: "label"  %>
                  <p class="control">
                    <%= form.text_area :body, class: "textarea", placeholder: "Add a comment..." %>
                  </p>
                </div>
                <nav class="level">
                  <div class="level-left">
                    <div class="level-item">
                      <%= form.submit submit, class: "button-is-info" %>
                    </div>
                    <div class="level-item">
                      <%= link_to 'Cancel', article_path(article), class: "button-is-light" %>
                    </div>
                  </div>
                </nav>
              </div>
            <% end %>
          </div>
      </article>
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<%= render 'form', article: @article, comment: @comment %>

app/views/comments/new.html.erb
<%= render 'form',
comment: @comment,
article: @article,
heading: '-New comment',
submit: 'Comment' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <section class="section'">
    <%= render "shared/navbar" %>
    <%= render "shared/flash" %>
    <%= yield %>
   </section>
  </body>
</html>

app/views/shared/_flash.html.erb
<div class="container">
  <div class="column is-multiline">
    <% flash.each do |name, message| %>

      <div class="column is-8 is-offset-2">
        <div class="notification has-text-centered is-<%= name %>">
          <%= message %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="container">
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <%= link_to 'My Blog', root_path, class: "navbar-item is-size-4 has-text-primary button is-primary is-outlined" %>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <% if logged_in? %>
              <%= link_to 'New Article', new_article_path, class: "button is-primary has-text-weight-bold" %>
              <%= link_to 'Log out', logout_path, method: :delete, class: "button is-primary has-text-weight-bold" %>
            <%else%>
              <%= link_to 'Log in', login_path, class: "button is-primary has-text-weight-bold"%>
              <%= link_to 'Sign up', users_signup_path, class: "button is-primary has-text-weight-bold" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content">
        <h1>New user</h1>
      </div>
    </div>

  <% if @user.errors.any? %>
    <div class="column is-6 is-offset-3">
      <article class="message is-danger">
        <div class="message-body">
          <p>
            <%= pluralize(@user.errors.count, 'error') %> prohibited this Article from being saved:
          </p><br>
            <% @user.errors.full_messages.each do |elem|%>
            <li><%= elem %></li>
          <% end %>
        </div>
      </article>
    </div>
  <% end %>

  <div class="column is-6 is-offset-3">
      <%= form_with model: @user, local: true do |form| %>
        <div class="field">
          <%= form.label :name, class: "label"  %>
          <div class="control">
            <%= form.text_field :name, class: "input", placeholder: "Name here"  %>
          </div>
        </div>

        <div class="field">
          <%= form.label :email, class: "label" %>
          <div class="control">
             <%= form.email_field :email, class: "input", placeholder: "Email here"  %>
          </div>
        </div>

        <div class="field">
          <%= form.label :password, class: "label" %>
          <div class="control">
             <%= form.password_field :password, class: "input", placeholder: "Password here"  %>
          </div>
        </div>

        <div class="field">
          <%= form.label :password_confirmation, class: "label" %>
          <div class="control">
             <%= form.password_field :password_confirmation, class: "input", placeholder: "Confirm here"  %>
          </div>
        </div>

        <div class="field is-grouped">
          <div class="control">
            <%= form.submit 'submit', class: "button is-link"  %>
          </div>
          <div class="control">
            <%= link_to 'Cancel', articles_path, class: "button is-link is-light" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content">
        <h1><%= @user.name  %></h1>
        <p><%= @user.email %></p>
      </div>
    </div>
  </div>